		<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/js/datatables/css/jquery.dataTables.min.css'); ?>
		<?php echo $this->partial('/index/header.phtml');?>
		<div class ="container">
			<div class ="row">
				<div class = "table-responsive">
					<table id = "publishtable" class = "table-striped table-hover">
						<thead>
							<tr class = "title">
								<th> ID</th>
								<th> Name</th>
								<th> Address</th>
								<th> Description</th>
								<th></th>
								<th></th>
						  	</tr>
					</thead>
				</table>
			<br/>

	<button id = "addpublisher" role= "button" data-toggle= "modal" data-target= "#publisherInsertForm">Add new publishers</button>
				 
<br/>

	<div class= "modal fade" id= "publisherInsertForm" role= "dialog">
  		<div class= "modal-dialog">
    		<div class= "modal-content">
      			<div class= "modal-header">
        			<button type="button" class="close" data-dismiss="modal">
          			<span aria-hidden="true">&times;</span>
          			<span class="sr-only">Close</span>
        			</button>
          			<h2 class= "modal-title" id= "myModalLable">Add Publisher</h2>
      			</div>
      			<div class="modal-body">
					<form action = "/Publishers/add" target = "_self" method = "POST" name= "insertPublisher" role= "form" >
  					<fieldset>

 					<div class="form-group">
 						<label for = "name">Name:</label> 
  						<input class="form-control" type="text" placeholder="Enter Company name" name="Name" minlength ="3" autofocus required />
  			 		</div>

 					<div class="form-group">
  						<label for="address">Address:</label>
  						<input class="form-control"type="text" placeholder="Enter Company Address" name="Address" required/>
  					</div>

 					<div class="form-group">
  						<label for="description">Description (optional):</label>
  						<textarea class="form-control" rows = "5" placeholder="write a description" name="Description"></textarea>
  					</div>
			</fieldset>
			</form>
		</div>
		<div class= "modal-footer">
        	<button type="button" class="btn btn-default"data-dismiss="modal">Close</button>
        	<button type="button" class="btn btn-primary" data-dismiss="modal"id= "publisherAdd">Add</button>
    	</div>
   	</div>
 </div>
</div>


<div class= "modal fade" id= "publisherUpdateForm" role= "dialog">
  <div class= "modal-dialog">
    <div class= "modal-content">
      <div class= "modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>
        <h2 class= "modal-title" id= "myModalLable">Edit Publisher</h2>
      </div>
      <div class="modal-body">
		<form  action = "/Publishers/save" target = "_self" method = "POST" name= "editPublisher" role= "form">
  		<fieldset>

    		<div class = "form-group">
 				<label for = "name">Name:</label>
 				<input class = "form-control formname" type="text" name="Name" minlength ="3" autofocus required />
  			</div>

  			<div class = "form-group">
  				<label for = "address">Address:</label>
  				<input class = "form-control formaddress" type="text" name="Address"required />
  			</div>

 			<div class="form-group">
  				<label for="description">Description (optional):</label>
  				<textarea class="form-control formdescription" rows = "5" name="Description"></textarea>
  			</div>

  			<div class = "form-group">
  				<input class = "formid" type="hidden" name="id"/>
			</div>
	</fieldset>
	</form>
</div>
<div class= "modal-footer">
  <button type="button" class="btn btn-default"data-dismiss="modal">Close</button>
  <button type="button" class="btn btn-primary" data-dismiss="modal"id= "publisherEdit">Save changes</button>
      	</div>
    </div>
  </div>
</div>

<div class= "modal fade" id= "publisherDeleteForm" role= "dialog">
  <div class= "modal-dialog">
    <div class= "modal-content">
      <div class= "modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>
        <h2 class= "modal-title" id= "myModalLable">Delete Publisher</h2>
      </div>
      <div class="modal-body">
        <p id= "warning"></p>
      </div>
      <div class= "modal-footer">
        <form action="/publishers/remove" name="deletePublisher" method="post">
          <input type="hidden" name="id"/>
          <input id="publisherDelete" type="submit"class="btn btn-primary" data-dismiss="modal" name="del" value="Yes" />
          <input type="submit" class="btn btn-default" data-dismiss="modal" name="del" value="No" />
        </form>
      </div>
    </div>
  </div>
</div>


					</div>
				</div>
			</div>
		</div>
 <?php  $this->headScript()->prependFile( $this->baseUrl("/js/datatables/js/jquery.dataTables.min.js")); ?>
 <?php  $this->headScript()->prependFile( $this->baseUrl("/js/publishers.js")); ?>