		<nav class="navbar navbar-default">
  			<div class="container-fluid">
    		<div class="navbar-header">
      <a class="navbar-brand" style = "color: #ffcc00; font-size: 40px; font-style : oblique;"href="/index">Wesam</a>
    </div>
    <ul class="nav navbar-nav">
      <li ><a href="/index" class ="navbar-link">Home</a></li>
      <li><a href="/auther/index" class ="navbar-link">Authers</a></li>
      <li><a href="/book/index" class ="navbar-link">Books</a></li>
      <li><a href="/Datatable/index" class ="navbar-link">Authers data table</a></li>
      <li><a href="/Publishers/index" class ="navbar-link">publishers data table</a></li>


    </ul>

    <ul class="nav navbar-nav navbar-right">
    <form class="navbar-form navbar-left">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">
           Search</button>
    </form>
      
  </ul>
  </div>
</nav>
