<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css'); ?>
<?php echo $this->partial('/index/header.phtml');?>
		<div class ="container">
			<a type = "button" id = "addbook" role= "button" data-toggle= "modal" data-target= "#bookInsertForm">Add new book</a> <br/><br/>
			<div class ="row">
				<div class = "table-responsive">
					<table id = "table2" class = "table table-bordered table-condensed table-responsive">
							<tr class = "title" id ="book">
								<th> ID</th>
								<th> Name</th>
								<th>Auther_ID</th>
					 			<th></th>
								<th></th>
							</tr>

				  <?php $authers = new Application_Model_DbTable_Authers();
				   		foreach ($this->book as $bookrow) :
				  		$sql = $authers->select()
        				->where('id ='.$bookrow['Auther_ID'].'' ); 
        				$result= $authers->fetchAll($sql);
        				$resultRow= $result->toArray();
						?>
							
 						<tr class = "active" id = "<?php echo $bookrow['ID']?>">
							<td class = "id"> <?php echo $bookrow ['ID'] ; ?></td>
							<td class ="name" id="book"> <?php echo $bookrow ['Name'] ; ?></td>
							<td class = "auther" data-id= "<?= $resultRow[0]['ID']  ?>">
							<?php echo $resultRow[0]["Name"];?> </td>
							<td>   <button id ="updatebook" role= "button" data-toggle= "modal" data-target= "#bookUpdateForm">update</button></td>
							<td>   <button id = "deletebook" role= "button" data-toggle= "modal" data-target= "#bookDeleteForm">delete</button></td>
						</tr>
					<?php endforeach ?>
												
					</table>
					<br/>



<div class= "modal fade" id= "bookInsertForm" role= "dialog">
  <div class= "modal-dialog">
    <div class= "modal-content">
      <div class= "modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>
          <h2 class= "modal-title" id= "myModalLable">Add Book</h2>
      </div>
      <div class="modal-body">
 		<form  action = "/book/add" target = "_self" method = "POST" name= "insertBook" role "form" >
 		<fieldset>
		<div class="form-group">
    		<label for= "name">Name:</label>
    		<input class = "form-control" type="text" placeholder = "Book name" name="Name" minlength= "2"  autofocus required/>
		</div>
		<div class="form-group">
      		<label for = "auther">Auther:</label>
	  		<select class = "form-control" name = "Auther_ID"required>
      			<option value = "" disabled hidden selected>-Select Auther-</option>
				<?php foreach ($this->auther as $autherrow) :?>
				<option value=<?= $autherrow['ID']?>><?= $autherrow ['Name'] ; ?></option>
				<?php endforeach ?>
      		</select>
		</div>
     	</fieldset>
	</form>
</div>
<div class= "modal-footer">
        <button type="button" class="btn btn-default"data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" data-dismiss="modal"id= "booksubmitbuttonAdd">Add</button>
    </div>
   </div>
 </div>
</div>


<div class= "modal fade" id= "bookUpdateForm" role= "dialog">
  <div class= "modal-dialog">
    <div class= "modal-content">
      <div class= "modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>
        <h2 class= "modal-title" id= "myModalLable">Edit Book</h2>
      </div>
      <div class="modal-body">
  		<form  action = "/book/save" target = "_self" method = "POST" name= "editBook" role= "form" >
    	<fieldset>
      		<div class = "form-group">
				<label for = "name">Name:</label>
				<input class = "form-control formname" type="text" name="Name" minlength="2" autofocus required />
  			</div>
			<div class = "form-group">
  				<label for = "auther">Auther:</label>
	  			<select class = "form-control updateBook" name = "Auther_ID" >
				<?php foreach($this->auther as $autherrow):?>
				<option class = "formauther" value = <?= $autherrow['ID'] ?>> <?= $autherrow ['Name'] ; ?></option>
				<?php endforeach ?>
				</select>
			</div>
			<div class = "form-group">				
  				<input class = "formid" type="hidden" name="id">
			</div>
		 </fieldset>
		</form>
	</div>
	<div class= "modal-footer">
    	<button type="button" class="btn btn-default"data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" data-dismiss="modal"id= "booksubmitbuttonEdit">Save changes</button>
   			</div>
 		</div>
	</div>
</div>

<div class= "modal fade" id= "bookDeleteForm" role= "dialog">
  <div class= "modal-dialog">
    <div class= "modal-content">
      <div class= "modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>
        <h2 class= "modal-title" id= "myModalLable">Delete Book</h2>
      </div>
      <div class="modal-body">
        <p id= "warning"></p>
      </div>
      <div class= "modal-footer">
        <form action="/book/remove" name="deleteBook" method="post">
          <input type="hidden" name="id"/>
          <input id="booksubmitbuttonDelete" type="submit"class="btn btn-primary" data-dismiss="modal" name="del" value="Yes" />
          <input type="submit" class="btn btn-default" data-dismiss="modal" name="del" value="No" />
        </form>
      </div>
    </div>
  </div>
</div>


</div>
</div>
</div>
