		<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/js/datatables/css/jquery.dataTables.min.css'); ?>
		<?php echo $this->partial('/index/header.phtml');?>
		<div class ="container">
			<div class ="row">
				<div class = "table-responsive">
					<table id = "table1" class = "table-striped table-hover">
						<thead>
							<tr class = "title">
								<th> ID</th>
								<th> Name</th>
								<th> Email</th>
								<th> actions</th>
								<th></th>
								<th></th>
						  	</tr>
					</thead>
				</table>
			<br/>

	<button id = "addauther" role= "button" data-toggle= "modal" data-target= "#insertForm">Add new author</button>
				 
<br/>

<div class= "modal fade" id= "insertForm" role= "dialog">
  <div class= "modal-dialog">
    <div class= "modal-content">
      <div class= "modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>
          <h2 class= "modal-title" id= "myModalLable">Add Author</h2>
      </div>
      <div class="modal-body">
	<form action = "/Datatable/add" target = "_self" method = "POST" name= "insert" role= "form" >
  		<fieldset>
			<div class="form-group">
 					<label for = "name">Name:</label> 
  					<input class="form-control" type="text" placeholder="Enter name" name="Name" minlength ="2" autofocus required />
  			 	</div>

 				<div class="form-group">
  					<label for="email">Email:</label>
  					<input class="form-control"type="email" placeholder="Enter email" name="E_mail" required />
  				</div>

		</fieldset>
	</form>
</div>
	<div class= "modal-footer">
        <button type="button" class="btn btn-default"data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id= "datatableAdd">Add</button>
    </div>
   </div>
 </div>
</div>


<div class= "modal fade" id= "updateForm" role= "dialog">
  <div class= "modal-dialog">
    <div class= "modal-content">
      <div class= "modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>
        <h2 class= "modal-title" id= "myModalLable">Edit Author</h2>
      </div>
      <div class="modal-body">
		<form action = "/Datatable/save" target = "_self" method = "POST" name= "update" role= "form" >
  		<fieldset>

    		<div class = "form-group">
 				<label for = "name">Name:</label>
 				<input class = "form-control formname" type="text" name="Name" minlength ="2" autofocus required />
  			</div>

  			<div class = "form-group">
  				<label for = "email">Email:</label>
  				<input class = "form-control formemail" type="email" name="E_mail"required />
  			</div>

  			<div class = "form-group">
  				<input class = "formid" type="hidden" name="id"/>
			</div>
	</fieldset>
</form>
</div>
	<div class= "modal-footer">
        	<button type="button" class="btn btn-default"data-dismiss="modal">Close</button>
        	<button type="button" class="btn btn-primary" id= "datatableEdit">Save changes</button>
      	</div>
    </div>
  </div>
</div>

<div class= "modal fade" id= "deleteForm" role= "dialog">
  <div class= "modal-dialog">
    <div class= "modal-content">
      <div class= "modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>
        <h2 class= "modal-title" id= "myModalLable">Delete Author</h2>
      </div>
      <div class="modal-body">
        <p id= "warning"></p>
      </div>
      <div class= "modal-footer">
        <form action="/auther/remove" name="delete" method="post">
          <input type="hidden" name="id"/>
          <input id="datatableDelete" type="submit"class="btn btn-primary" data-dismiss="modal" name="del" value="Yes" />
          <input type="submit" class="btn btn-default" data-dismiss="modal" name="del" value="No" />
        </form>
      </div>
    </div>
  </div>
</div>


					</div>
				</div>
			</div>
		</div>

 <?php  $this->headScript()->prependFile( $this->baseUrl("/js/datatables/js/jquery.dataTables.min.js")); ?>
 <?php  $this->headScript()->prependFile( $this->baseUrl("/js/authersdatatable.js")); ?>