		<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/js/datatables/css/jquery.dataTables.min.css'); ?>
		<?php echo $this->partial('/index/header.phtml');?>
		<div class ="container">
			<div class ="row">
				<div class = "table-responsive">
					<table id = "table1" class = "table-striped table-hover">
						<thead>
							<tr class = "title">
								<th> ID</th>
								<th> Name</th>
								<th> Email</th>
								<th> actions</th>
								<th></th>
								<th></th>
						  	</tr>
					</thead>
				</table>
			<br/>

	<button type = "button" id = "add">Add</button>
				 
<br/>

<div id = "div1" class = "hidden">
	<form action = "/Datatable/add" target = "_self" method = "POST" class = "ajax" >
  		<fieldset>
    		<legend>Auther information:</legend>

 				<div class="form-group">
 					<label for = "name">Name:</label> 
  					<input class="form-control" type="text" placeholder="Enter name" name="Name" minlength ="2" autofocus required />
  			 	</div>

 				<div class="form-group">
  					<label for="email">Email:</label>
  					<input class="form-control"type="email" placeholder="Enter email" name="E_mail" required />
  				</div>

   				<input type="submit" value="Submit">
		</fieldset>
	</form>
</div>


<div class = "hidden" id = "div2">

	<form class = "ajax2" action = "/Datatable/save" target = "_self" method = "POST" >
  		<fieldset>
    		<legend>Auther information:</legend>

    		<div class = "form-group">
 				<label for = "name">Name:</label>
 				<input class = "form-control formname" type="text" name="Name" minlength ="2" autofocus required />
  			</div>

  			<div class = "form-group">
  				<label for = "email">Email:</label>
  				<input class = "form-control formemail" type="email" name="E_mail"required />
  			</div>

  			<div class = "form-group">
  				<input class = "formid" type="hidden" name="id"/>
  				<input type="submit" value="update"/>
			</div>
	</fieldset>
						</form>
					</div>
				</div>
			</div>
		</div>

 <?php  $this->headScript()->prependFile( $this->baseUrl("/js/validate/dist/jquery.validate.min.js")); ?>
 <?php  $this->headScript()->prependFile( $this->baseUrl("/js/jquery.form.min.js")); ?>
 <?php  $this->headScript()->prependFile( $this->baseUrl("/js/datatables/js/jquery.dataTables.min.js")); ?>
 <?php  $this->headScript()->prependFile( $this->baseUrl("/js/authersdatatable.js")); ?>